### ISSUE TITLE
Does this replace vikejs/vike-angular ?

### ISSUE THREAD

**Issue by lourot** [vikejs/vite-plugin-angular#1]
Does this replace https://github.com/vikejs/vike-angular ? I'm a bit confused, because:

1. The readme says it's a Vike integration
2. I don't see Vike in `package.json`

Is https://vike.dev/angular still correct?

**Comment by nitedani** [comment]
This is the Vite plugin used by vike-angular. An equivalent to @vitejs/plugin-react-swc, but for Angular. I don't want people to try use it without Vike, not work, and open issues. It's made with Vike support only in mind, so it can be less bloated than a full-fledged Vite Angular plugin(I intended to signal this with the Vike integration part in the readme). There is no official Vite plugin for Angular yet, it has to be implemented here. I hope, there will be an official plugin sooner or later, and this plugin can be removed.

The manual integration part on [vike.dev/angular](https://vike.dev/angular) is not correct anymore, it should link to the examples directory of this package, or even better, an example would be nice in the main Vike repo. The example can be copied from https://github.com/vikejs/vite-plugin-angular/tree/main/examples/vike-express, though it still needs a bit of polishing.

It's used here: https://github.com/vikejs/vike-angular/blob/main/examples/basic/vite.config.ts

**Comment by lourot** [comment]
I see, thanks!
